AAFC-BICoE/dina-base-api

.travis.yml
=> Feature #18340 Enable Travis CI

.travis.yml, checkstyle.xml, pom.xml
This adds the necessary maven configuration to run check style and spot bugs.
Travis has also been updated to run both check style and spot bugs.
=> Feature 18338 enable checkstyle and spotbugs

.travis.yml, pom.xml
Travis will now deploy the project artifact to Bin-tray maven repository on pushes to the master branch
=> Support 18384 publish artifact to bintray

pom.xml, src/main/java/ca/gc/aafc/dina/testsupport/DBBackedIntegrationTest.java, src/main/java/ca/gc/aafc/dina/testsupport/factories/TestableEntityFactory.java
Replaced seqdb with dina in our package hierarchy.
=> Support 18397 change package from seqdb to dina

src/main/java/ca/gc/aafc/dina/entity/SoftDeletable.java, src/main/java/ca/gc/aafc/dina/jpa/BaseDAO.java, src/main/java/ca/gc/aafc/dina/repository/GoneException.java
Added common classes from object-store.
=> Feature #18877 Move common classes from object-store

pom.xml
Updated dependencies and removed unnecessary properties
=> Support #18887 Update dependencies

README.md, docs/design.adoc, docs/general_design.adoc, docs/index.adoc, docs/layers.plantuml, docs/testing.adoc, pom.xml
Moved informations related to general DINA modules.
=> Support #18889 Move AAFC DINA implementation guidelines

README.md
Added BinTray information to the README
=> Support #18931 Update README with package information

src/main/java/ca/gc/aafc/dina/jpa/BaseDAO.java, src/test/java/ca/gc/aafc/dina/entity/Department.java, src/test/java/ca/gc/aafc/dina/entity/DepartmentType.java, src/test/java/ca/gc/aafc/dina/jpa/BaseDAOIT.java
Added basic test coverage for BaseDAO class.
=> Feature #19066 Add test coverage for BaseDAO

README.md, pom.xml
Update version to 0.23 in pom and README
=> Feature #19130 Release 0.23

dina-base-api/pom.xml, dina-test-support/pom.xml, pom.xml
=> bug_19132_revert_use_of_global_version_in_pom

dina-base-api/pom.xml, dina-test-support/pom.xml, dina-test-support/src/main/java/ca/gc/aafc/dina/testsupport/DBBackedIntegrationTest.java, dina-test-support/src/test/java/ca/gc/aafc/dina/testsupport/DBBackedIntegrationTestTest.java, dina-test-support/src/test/java/ca/gc/aafc/dina/testsupport/TestConfiguration.java, dina-test-support/src/test/java/ca/gc/aafc/dina/testsupport/entity/ComplexObject.java, pom.xml
Implemented:
- Common sub module dependencies lifted to parent.
- remove method renamed and given java docs
- deleteByProperty added
- small test suite setup ( slight overhead from setup )
=> 19134 add delete by property

dina-base-api/src/main/java/ca/gc/aafc/dina/entity/DinaEntity.java, dina-base-api/src/test/java/ca/gc/aafc/dina/entity/ComplexObject.java
- Add DinaEntity interface with a small use case in tests
=> 19183_Dina_Entity_interface

README.md, dina-base-api/pom.xml, dina-test-support/pom.xml, pom.xml
Update version number in pom files.
=> Support #19212 Release 0.25

.gitignore, dina-base-api/pom.xml, dina-base-api/src/main/java/ca/gc/aafc/dina/security/KeycloakAuthConfig.java, dina-base-api/src/main/java/ca/gc/aafc/dina/security/KeycloakDisabledAuthConfig.java
Added Keycloak configuration classes from object-store.
=> Support #19215 Move Keycloak ConfigurerAdapter from object-store

dina-base-api/pom.xml, dina-base-api/src/test/java/ca/gc/aafc/dina/filter/RsqlFilterHandlerIT.java, pom.xml
Updated SpringBoot, Checkstyle and Crnk. Fixed RsqlFilterHandlerIT since the signature of querySpecUrlMapper.deserialize changed.
=> Support #19269 Update dependencies

dina-base-api/src/main/java/ca/gc/aafc/dina/entity/DinaEntity.java, dina-base-api/src/test/java/ca/gc/aafc/dina/entity/ComplexObject.java, dina-base-api/src/test/java/ca/gc/aafc/dina/entity/Department.java, dina-base-api/src/test/java/ca/gc/aafc/dina/jpa/BaseDAOIT.java
=> Bug #19315 DinaEntity should use Integer for getId, Changed Long to

dina-base-api/src/main/java/ca/gc/aafc/dina/repository/DinaRepository.java, dina-base-api/src/main/java/ca/gc/aafc/dina/service/DinaService.java, dina-base-api/src/test/java/ca/gc/aafc/dina/jpa/DinaServiceTest.java, dina-base-api/src/test/java/ca/gc/aafc/dina/repository/DinaRepositoryIT.java
Simply moves dina service to service package
=> 19382_Move_Dina_Service

dina-base-api/src/test/java/ca/gc/aafc/dina/TestConfiguration.java, dina-base-api/src/test/java/ca/gc/aafc/dina/service/DinaServiceTest.java
Move dina service test to service package
=> 19387 move dina service test

dina-base-api/src/main/java/ca/gc/aafc/dina/security/DinaAuthenticatedUser.java, dina-base-api/src/main/java/ca/gc/aafc/dina/security/KeycloakAuthConfig.java, dina-base-api/src/test/java/ca/gc/aafc/dina/security/KeycloakCurrentUserIT.java, docs/authentication.adoc, docs/index.adoc
https://redmine.biodiversity.agr.gc.ca/issues/19274
-Added injectable currentUser with the username and agent identifier.
-Added test
=> Feedback Feature #19274 Extract agent-identifier from Keycloak token

dina-base-api/src/main/java/ca/gc/aafc/dina/DinaBaseApiAutoConfiguration.java, dina-base-api/src/test/java/ca/gc/aafc/dina/locale/LocaleController.java, dina-base-api/src/test/java/ca/gc/aafc/dina/locale/LocaleResolverTest.java, dina-base-api/src/test/resources/messages.properties, dina-base-api/src/test/resources/messages_fr.properties
Add LocaleInterceptor and LocaleResolver to base configurations.
=> 19327 add locale resolver locale change interceptor

dina-base-api/src/main/java/ca/gc/aafc/dina/security/KeycloakAuthConfig.java, dina-base-api/src/test/java/ca/gc/aafc/dina/security/KeycloakCurrentUserIT.java
remove prefixed forward slashes from groups
=> 19487_groups_prefixed_forward_slashes

pom.xml
- Bump version to 2.3.1
- add validation dependency now required with 2.3.x
=> 19451_update_springboot_version

dina-base-api/src/main/java/ca/gc/aafc/dina/mapper/CustomFieldHandler.java, dina-base-api/src/main/java/ca/gc/aafc/dina/mapper/DinaMapper.java
Adjust custom field handler interface for a more generic method to resolve fields
Needed for ticket 19380
=> 19627 adjust custom handler resolve fields

dina-base-api/src/main/java/ca/gc/aafc/dina/mapper/CustomFieldHandler.java, dina-base-api/src/main/java/ca/gc/aafc/dina/mapper/DinaMapper.java, dina-base-api/src/test/java/ca/gc/aafc/dina/TestConfiguration.java, dina-base-api/src/test/java/ca/gc/aafc/dina/mapper/DinaMapperTest.java
Enables the dina mapper to map all nested custom fields in an entity graph
=> 19380 dina mapper nested resolvers

dina-base-api/src/main/java/ca/gc/aafc/dina/security/DevUserConfig.java, dina-base-api/src/test/java/ca/gc/aafc/dina/security/DevUserConfigIT.java, docs/authentication.adoc
https://redmine.biodiversity.agr.gc.ca/issues/19429
-Added DevUserConfig.
=> Feedback Feature #19429 Add support for anonymous DinaAuthenticatedUser

dina-base-api/src/main/java/ca/gc/aafc/dina/filter/SimpleFilterHandler.java, dina-base-api/src/test/java/ca/gc/aafc/dina/filter/SimpleFilterHandlerIT.java
Simple filter handler can now build restrictions for == null and != null
Test coverage added
=> 19690 simple filter handler handle null expressions

dina-base-api/src/main/java/ca/gc/aafc/dina/entity/DinaEntity.java
group added to the interface with default value (null)
=> Support #19663 Add group to DinaEntity

.travis.yml
Added missing config for github pages
=> Support #19634 Fix documentation generation issue

dina-base-api/src/main/java/ca/gc/aafc/dina/security/DinaAuthenticatedUser.java, dina-base-api/src/test/java/ca/gc/aafc/dina/security/DinaAuthenticatedUserTest.java
Prevent NPE on empty roles per groups
=> Support #19773 Potential NPE in DinaAuthenticatedUser

dina-base-api/src/main/java/ca/gc/aafc/dina/service/DinaService.java, dina-base-api/src/test/java/ca/gc/aafc/dina/repository/DinaRepositoryIT.java, dina-base-api/src/test/java/ca/gc/aafc/dina/service/DinaServiceTest.java
Remove return types for dina service PRE methods, and add default implementations to do nothing
=> 19781_dina_service_pre_return_type_and_default

dina-base-api/src/main/java/ca/gc/aafc/dina/mapper/DinaMapper.java, dina-base-api/src/test/java/ca/gc/aafc/dina/mapper/DinaMapperTest.java
Allows the dina mapper to map the circular relations without a stack overflow
=> 19760 stack overflow dina mapper circular relation

dina-base-api/src/main/java/ca/gc/aafc/dina/repository/DinaRepository.java, dina-base-api/src/test/java/ca/gc/aafc/dina/dto/PersonDTO.java
- Updates the dina repo to exclude fields that are final in mapping
- Test case added for the edge case
=> 19849_dina_repo_includes_constants_in_mapping

dina-base-api/src/main/java/ca/gc/aafc/dina/mapper/DinaMapper.java
- Creates a null safe usage with Sets.union
=> 19848_dina_mapper_resolve_hibernate_proxy

docs/general_design.adoc
add dina layers to documentation
=> 19845 add dina layers to documentation

dina-base-api/src/main/java/ca/gc/aafc/dina/repository/DinaRepository.java, dina-base-api/src/test/java/ca/gc/aafc/dina/TestConfiguration.java, dina-base-api/src/test/java/ca/gc/aafc/dina/auditing/DinaRepoAuditingIT.java, dina-base-api/src/test/java/ca/gc/aafc/dina/dto/PersonDTO.java
Adjusts the Dina repo to accept an audit service class, which if present will perform the auditing operations for CUD operations.
=> 19996 dina repo uses audit service

.travis.yml
Run dependency-check only on dev branch
=> Support #20068 Run dependency-check in a cron job

docs/auditing.adoc, docs/index.adoc
=> 19997 add audit docs

docs/index.adoc, docs/release.adoc
Added docs regarding the release of dina-base-api
=> Support #19966 Document how to release dina-base-api

pom.xml
Configure Maven source plugin to produce source jar.
=> Support #20086 Create source artifact

dina-base-api/src/main/java/ca/gc/aafc/dina/mapper/DinaMapper.java, dina-base-api/src/test/java/ca/gc/aafc/dina/repository/DinaRepositoryIT.java
Reverts AAFC-BICoE/dina-base-api#96
=> Revert "Feedback Bug #20144 findOne/findAll should include shallow references…"

dina-test-support/pom.xml, dina-test-support/src/main/java/ca/gc/aafc/dina/testsupport/specs/OpenAPI3Assertions.java, dina-test-support/src/test/resources/managedAttribute.yaml, pom.xml
Dependecies update to fixes code and tests related to OpenApi4j
=> Support #20164 Dependencies update

dina-base-api/src/main/java/ca/gc/aafc/dina/security/spring/DinaPermissionEvaluator.java, dina-base-api/src/test/java/ca/gc/aafc/dina/security/spring/DinaPermissionEvaluatorTest.java
adds method hasDinaRole to the permission evaluator with a test suite to prove its usage is working.
=> 20218 add has dina role

.travis.yml, dina-test-support/pom.xml, dina-test-support/src/main/java/ca/gc/aafc/dina/testsupport/PostgresTestContainerInitializer.java, dina-test-support/src/test/java/ca/gc/aafc/dina/testsupport/ExampleDbBackedIntegrationTest.java, dina-test-support/src/test/resources/application.yml, docs/test_support.adoc
-Added PostgresTestContainerInitializer class to setup a postgres container for integration testing.
-Added docs.
-Fixed spotbugs issue in the PostgresTestContainerInitializer javadoc.
-Added Findbugs suppression for an instance method writing to a static field. Not my fault, I'm just following one of the official examples for testcontainers.
=> Feedback 20217

pom.xml
Updated Crnk to latest stable version
=> Support #20243 Update Crnk

dina-base-api/src/test/java/ca/gc/aafc/dina/TestDinaBaseApp.java, dina-base-api/src/test/java/ca/gc/aafc/dina/auditing/DinaRepoAuditingIT.java, dina-base-api/src/test/java/ca/gc/aafc/dina/exceptionmapping/ConstraintViolationExceptionMapperIT.java, dina-base-api/src/test/java/ca/gc/aafc/dina/exceptionmapping/DataIntegrityViolationExceptionMapperIT.java, dina-base-api/src/test/java/ca/gc/aafc/dina/filter/RsqlFilterHandlerIT.java, dina-base-api/src/test/java/ca/gc/aafc/dina/filter/SimpleFilterHandlerIT.java, dina-base-api/src/test/java/ca/gc/aafc/dina/jpa/BaseDAOIT.java, dina-base-api/src/test/java/ca/gc/aafc/dina/json/DateDeserializerIT.java, dina-base-api/src/test/java/ca/gc/aafc/dina/jsonapi/OperationJsonApiIT.java, dina-base-api/src/test/java/ca/gc/aafc/dina/repository/AuditSnapshotRepositoryIT.java, dina-base-api/src/test/java/ca/gc/aafc/dina/repository/DinaRepositoryIT.java, dina-base-api/src/test/java/ca/gc/aafc/dina/repository/JpaRelationshipRepositoryIT.java, dina-base-api/src/test/java/ca/gc/aafc/dina/repository/JpaResourceRepositoryIT.java, dina-base-api/src/test/java/ca/gc/aafc/dina/repository/ReadOnlyDinaRepositoryIT.java, dina-base-api/src/test/java/ca/gc/aafc/dina/repository/meta/JpaTotalMetaInformationProviderIT.java, dina-base-api/src/test/java/ca/gc/aafc/dina/security/DevUserConfigIT.java, dina-base-api/src/test/java/ca/gc/aafc/dina/security/DinaGroupBasedPermissionsTest.java, dina-base-api/src/test/java/ca/gc/aafc/dina/security/KeycloakCurrentUserIT.java, dina-base-api/src/test/java/ca/gc/aafc/dina/service/AuditServiceIT.java, dina-base-api/src/test/java/ca/gc/aafc/dina/service/DinaServiceTest.java
Renamed TestConfiguration test class
=> Support #20281 Rename TestConfiguration

dina-test-support/src/main/java/ca/gc/aafc/dina/testsupport/BaseRestAssuredTest.java, dina-test-support/src/test/java/ca/gc/aafc/dina/testsupport/BaseRestAssuredTestIT.java
Added RestAssured option to log the response when assertion fails on Post, Patch and Operation.
=> Support #20263 Add RestAssured ifValidationFails

dina-base-api/pom.xml
=> Feedback 20319

dina-base-api/src/main/java/ca/gc/aafc/dina/filter/DinaFilterResolver.java, dina-base-api/src/main/java/ca/gc/aafc/dina/repository/DinaRepository.java, dina-base-api/src/test/java/ca/gc/aafc/dina/dto/ChainDto.java, dina-base-api/src/test/java/ca/gc/aafc/dina/dto/ChainTemplateDto.java, dina-base-api/src/test/java/ca/gc/aafc/dina/entity/Chain.java, dina-base-api/src/test/java/ca/gc/aafc/dina/entity/ChainTemplate.java, dina-base-api/src/test/java/ca/gc/aafc/dina/jsonapi/DinaRepoEagerLoadingIT.java
Major changes:
- Find all always eager loads included relations
- Find one uses find all
Tests added to prove the edge case
=> 20400 dina repo eager load relations

.gitignore, dina-test-support/src/main/java/ca/gc/aafc/dina/testsupport/BaseRestAssuredTest.java, dina-test-support/src/main/java/ca/gc/aafc/dina/testsupport/jsonapi/JsonAPITestHelper.java, dina-test-support/src/test/java/ca/gc/aafc/dina/testsupport/BaseRestAssuredTestIT.java, dina-test-support/src/test/java/ca/gc/aafc/dina/testsupport/jsonapi/JsonAPITestHelperTest.java
Added mostly simplified method signature and new useful methods
=> Support #20461 Add simplified BaseRestAssuredTest methods

dina-base-api/src/main/java/ca/gc/aafc/dina/repository/DinaRepository.java
add java docs for some dina repo methods
=> 20168 document find one

dina-base-api/src/main/java/ca/gc/aafc/dina/repository/DinaRepository.java, dina-base-api/src/test/java/ca/gc/aafc/dina/dto/DepartmentDto.java, dina-base-api/src/test/java/ca/gc/aafc/dina/entity/Department.java, dina-base-api/src/test/java/ca/gc/aafc/dina/repository/DinaRepositoryIT.java
-Fixed eager-loading skippping code for external relations.
-Added test.
=> Feedback Bug_20605_Nested_includes_failing

dina-base-api/src/main/java/ca/gc/aafc/dina/repository/DinaRepository.java, dina-base-api/src/test/java/ca/gc/aafc/dina/auditing/DinaRepoAuditingIT.java, dina-base-api/src/test/java/ca/gc/aafc/dina/dto/DepartmentDto.java
Fixes a small issue when auditing the relation of a newly created resource that has a relationship to another entity that can be audited.
A test suite has been updated for the edge case
=> 20576 auditing relations error

dina-base-api/src/main/java/ca/gc/aafc/dina/jpa/BaseDAO.java, dina-base-api/src/main/java/ca/gc/aafc/dina/service/DinaService.java, dina-base-api/src/test/java/ca/gc/aafc/dina/jpa/BaseDAOIT.java, dina-base-api/src/test/java/ca/gc/aafc/dina/service/DinaServiceTest.java
-Added exists method to DinaService.
-Changed BaseDao exists method to use 'exists' SQL query.
=> Feedback 20606

dina-base-api/src/main/java/ca/gc/aafc/dina/json/TrimStringDeserializer.java, dina-base-api/src/test/java/ca/gc/aafc/dina/json/TrimStringDeserializerIT.java
Implemented using Jackson StringDeserializer and tested using SpringBoot provided ObjectMapper
=> Support #20754 Trim all strings on Jackson deserialize

dina-base-api/src/main/java/ca/gc/aafc/dina/security/DinaRole.java
=> Feedbacl 20790

dina-base-api/src/main/java/ca/gc/aafc/dina/mapper/DinaMapper.java, dina-base-api/src/main/java/ca/gc/aafc/dina/mapper/DinaMappingRegistry.java, dina-base-api/src/test/java/ca/gc/aafc/dina/mapper/DinaMapperTest.java
revert use of guava for mapping layer
=> 20770 remove guava maps from mapping layer

dina-base-api/src/main/java/ca/gc/aafc/dina/mapper/DinaMappingLayer.java, dina-base-api/src/main/java/ca/gc/aafc/dina/repository/DinaRepository.java, dina-base-api/src/main/java/ca/gc/aafc/dina/repository/ReadOnlyDinaRepository.java, dina-base-api/src/main/java/ca/gc/aafc/dina/service/DefaultDinaService.java, dina-base-api/src/main/java/ca/gc/aafc/dina/service/DinaService.java, dina-base-api/src/test/java/ca/gc/aafc/dina/TestDinaBaseApp.java, dina-base-api/src/test/java/ca/gc/aafc/dina/jsonapi/DinaRepoEagerLoadingIT.java, dina-base-api/src/test/java/ca/gc/aafc/dina/jsonapi/DinaRepoRestIT.java, dina-base-api/src/test/java/ca/gc/aafc/dina/mapper/DinaMappingLayerIT.java, dina-base-api/src/test/java/ca/gc/aafc/dina/repository/DinaRepositoryIT.java, dina-base-api/src/test/java/ca/gc/aafc/dina/service/DefaultDinaServiceTest.java
Extracts the DinaService as an interface and replaces the usage in the dina repo and dina mapping layer.
all previous tests should be passing to prove its usage.
=> 20803 dina service as interface

dina-base-api/src/main/java/ca/gc/aafc/dina/mapper/CustomFieldResolverSpec.java, dina-base-api/src/main/java/ca/gc/aafc/dina/mapper/JpaDtoMapper.java, dina-base-api/src/main/java/ca/gc/aafc/dina/repository/JpaDtoRepository.java, dina-base-api/src/main/java/ca/gc/aafc/dina/repository/JpaRelationshipRepository.java, dina-base-api/src/main/java/ca/gc/aafc/dina/repository/JpaResourceRepository.java, dina-base-api/src/main/java/ca/gc/aafc/dina/repository/meta/JpaMetaInformationProvider.java, dina-base-api/src/main/java/ca/gc/aafc/dina/repository/meta/JpaTotalMetaInformationProvider.java, dina-base-api/src/main/java/ca/gc/aafc/dina/util/TriConsumer.java, dina-base-api/src/main/java/ca/gc/aafc/dina/util/TriFunction.java
Labels classes as deprecated for future removal.
=> 20844 deprecate classes

dina-base-api/src/main/java/ca/gc/aafc/dina/mapper/CustomFieldHandler.java
adjust CustomFieldHandler resolveFields to prevent the copy of an internal map
=> 20867CustomFieldHandler  resolve fields copies internal map

docs/externalTypes.adoc
remove old CFR instructions from external types guide
=> 20911 update external type docs

dina-base-api/src/main/java/ca/gc/aafc/dina/mapper/CustomFieldAdapter.java, dina-base-api/src/main/java/ca/gc/aafc/dina/mapper/DinaFieldAdapter.java, dina-base-api/src/main/java/ca/gc/aafc/dina/mapper/DinaFieldAdapterHandler.java, dina-base-api/src/test/java/ca/gc/aafc/dina/mapper/DinaFieldAdapterHandlerTest.java
Introduces field adapter to replace CFRs,
proof of concept through the adapter handler.
adapter handler uses same pattern as CFR handler, should be swappable.
=> 21013 field adapters

dina-base-api/pom.xml, dina-test-support/pom.xml, pom.xml
=> Support #21040 Update dependencies

dina-base-api/src/main/java/ca/gc/aafc/dina/mapper/CustomFieldAdapter.java, dina-base-api/src/main/java/ca/gc/aafc/dina/mapper/DinaFieldAdapter.java, dina-base-api/src/main/java/ca/gc/aafc/dina/mapper/DinaFieldAdapterHandler.java, dina-base-api/src/main/java/ca/gc/aafc/dina/mapper/DinaMapper.java, dina-base-api/src/main/java/ca/gc/aafc/dina/mapper/DinaMappingRegistry.java, dina-base-api/src/main/java/ca/gc/aafc/dina/mapper/IgnoreDinaMapping.java, dina-base-api/src/main/java/ca/gc/aafc/dina/mapper/JpaDtoMapper.java, dina-base-api/src/test/java/ca/gc/aafc/dina/dto/DepartmentDto.java, dina-base-api/src/test/java/ca/gc/aafc/dina/dto/EmployeeDto.java, dina-base-api/src/test/java/ca/gc/aafc/dina/mapper/DinaFieldAdapterHandlerTest.java, dina-base-api/src/test/java/ca/gc/aafc/dina/mapper/DinaMapperTest.java
Adjust adapters and adapter handler to use a supplier
=> 21055 field adapter missing link

owasp-suppression.xml
=> 21071 fix owasp

dina-base-api/src/main/java/ca/gc/aafc/dina/repository/DinaRepository.java, dina-base-api/src/main/java/ca/gc/aafc/dina/repository/ReadOnlyDinaRepository.java, dina-base-api/src/main/java/ca/gc/aafc/dina/repository/meta/DinaMetaInfo.java, dina-base-api/src/test/java/ca/gc/aafc/dina/TestDinaBaseApp.java, dina-base-api/src/test/java/ca/gc/aafc/dina/jsonapi/DinaRepoEagerLoadingIT.java, dina-base-api/src/test/java/ca/gc/aafc/dina/jsonapi/DinaRepoRestIT.java, dina-base-api/src/test/java/ca/gc/aafc/dina/mapper/DinaMappingLayerIT.java, dina-base-api/src/test/java/ca/gc/aafc/dina/repository/DinaRepositoryIT.java
-Added BuildProperties to DinaRepository.
-getMetaInformation gets version from BuildProperties.
-Added tests, updated DinaRepository constructor calls.
=> Feedback 21039

dina-base-api/src/main/java/ca/gc/aafc/dina/mapper/DinaMappingLayer.java, dina-base-api/src/main/java/ca/gc/aafc/dina/service/DefaultDinaService.java, dina-base-api/src/main/java/ca/gc/aafc/dina/service/DinaService.java
- Rename to getReferenceByNaturalId , same as BaseDAO
=> Support-21096-Rename-DinaService-findOneReferenceByNaturalId

dina-base-api/pom.xml, pom.xml
=> 21210 update spring boot

owasp-suppression.xml, pom.xml
=> 21309 Fix owaps issue

dina-base-api/src/test/java/ca/gc/aafc/dina/jsonapi/DinaRepoRestIT.java, dina-test-support/pom.xml, pom.xml
Updated dependencies and fixed issue with DinaRepoRestIT
=> 21327 Update dependencies

dina-base-api/src/main/java/ca/gc/aafc/dina/mapper/DinaMapper.java, dina-base-api/src/main/java/ca/gc/aafc/dina/mapper/DinaMappingRegistry.java, dina-base-api/src/test/java/ca/gc/aafc/dina/mapper/DinaMappingRegistryTest.java
Move field handler tracking from mapper to the registry
=> 21346 move field handlers to dina registry

dina-base-api/src/main/java/ca/gc/aafc/dina/mapper/DinaMappingLayer.java, dina-base-api/src/test/java/ca/gc/aafc/dina/dto/ProjectDTO.java, dina-base-api/src/test/java/ca/gc/aafc/dina/entity/Project.java, dina-base-api/src/test/java/ca/gc/aafc/dina/mapper/DinaMappingLayerIT.java, dina-base-api/src/test/java/ca/gc/aafc/dina/mapper/DinaMappingRegistryTest.java
Update the mapping layer to map collections of external types
=> 21371 support collections of external types

dina-base-api/src/main/java/ca/gc/aafc/dina/security/DinaRole.java
Use enum to hold the key cloak definition
=> 21724 dina role enum support for keycloak role

.github/workflows/maven.yml, README.md
updated gh action workflow file and updated README
=> 21769 Update GitHub action file to publish on Maven Central

dina-test-support/pom.xml, owasp-suppression.xml, pom.xml
=> 21823 Update dependencies

dina-base-api/src/main/java/ca/gc/aafc/dina/json/SanitizeStringDeserializer.java, dina-base-api/src/test/java/ca/gc/aafc/dina/json/SanitizeStringDeserializerIT.java
-Renamed TrimStringDeserializer to SanitizeStringDeserializer.
-Changed trim() call to strip().
=> Support_21867_TrimStringDeserializer_should_be_renamed_and_improved

README.md
added badge and remove hardcoded version
=> 21785 Add Maven Central badge

pom.xml
Updated Keycloak version to 12.0.4
=> Support #21312 - Update Keycloak to 12.0.x

dina-base-api/src/main/java/ca/gc/aafc/dina/exceptionmapping/ConstraintViolationExceptionMapper.java, dina-base-api/src/main/java/ca/gc/aafc/dina/jpa/BaseDAO.java, dina-base-api/src/main/java/ca/gc/aafc/dina/service/DefaultDinaService.java, dina-base-api/src/main/java/ca/gc/aafc/dina/service/DinaService.java, dina-base-api/src/main/java/ca/gc/aafc/dina/service/OnCreate.java, dina-base-api/src/main/java/ca/gc/aafc/dina/service/OnUpdate.java, dina-base-api/src/main/resources/application.properties, dina-base-api/src/test/java/ca/gc/aafc/dina/DinaUserConfig.java, dina-base-api/src/test/java/ca/gc/aafc/dina/TestDinaBaseApp.java, dina-base-api/src/test/java/ca/gc/aafc/dina/entity/Chain.java, dina-base-api/src/test/java/ca/gc/aafc/dina/entity/ChainTemplate.java, dina-base-api/src/test/java/ca/gc/aafc/dina/entity/Department.java, dina-base-api/src/test/java/ca/gc/aafc/dina/jpa/BaseDAOIT.java, dina-base-api/src/test/java/ca/gc/aafc/dina/jsonapi/DinaRepoEagerLoadingIT.java, dina-base-api/src/test/java/ca/gc/aafc/dina/jsonapi/DinaRepoRestIT.java, dina-base-api/src/test/java/ca/gc/aafc/dina/mapper/DinaMappingLayerIT.java, dina-base-api/src/test/java/ca/gc/aafc/dina/repository/meta/AttributeMetaInfoProviderRestIT.java, dina-base-api/src/test/java/ca/gc/aafc/dina/service/DefaultDinaServiceTest.java
https://redmine.biodiversity.agr.gc.ca/issues/22198
=> 22198 change validation mechanism

docs/design.adoc, docs/index.adoc, docs/validation.adoc
https://redmine.biodiversity.agr.gc.ca/issues/22239
=> 22239 add documentation on validation implementation

dina-base-api/src/main/java/ca/gc/aafc/dina/exceptionmapping/ConstraintViolationExceptionMapper.java, dina-base-api/src/test/java/ca/gc/aafc/dina/exceptionmapping/ConstraintViolationExceptionMapperIT.java
https://redmine.biodiversity.agr.gc.ca/issues/22256
=> 22256 change constraintviolationexceptionmapper to return more information

dina-base-api/src/main/java/ca/gc/aafc/dina/entity/DinaEntity.java, dina-base-api/src/test/java/ca/gc/aafc/dina/entity/ComplexObject.java, dina-base-api/src/test/java/ca/gc/aafc/dina/entity/Employee.java, dina-base-api/src/test/java/ca/gc/aafc/dina/repository/meta/AttributeMetaInfoProviderRestIT.java
https://redmine.biodiversity.agr.gc.ca/issues/22325
=> 22325_add_uuid_to_dinaentity

pom.xml
SpringBoot, SpotBug, Checkstyle and dependency-check
=> Support #22356 Update dependencies

dina-base-api/src/main/java/ca/gc/aafc/dina/SupportedLanguagesConfiguration.java, dina-base-api/src/main/resources/supported-languages.yml, dina-base-api/src/test/java/ca/gc/aafc/dina/locale/SupportedLanguagesConfigurationTest.java, dina-base-api/src/test/resources/supported-languages.yml
https://redmine.biodiversity.agr.gc.ca/issues/19141
=> 19144 add supported language

dina-base-api/pom.xml
=> Feedback 22332

dina-base-api/src/main/java/ca/gc/aafc/dina/repository/meta/AttributeMetaInfoProvider.java, dina-base-api/src/test/java/ca/gc/aafc/dina/repository/meta/AttributeMetaInfoProviderRestIT.java
https://redmine.biodiversity.agr.gc.ca/issues/20869
=> 20869 define proper way to return warnings

dina-base-api/src/main/java/ca/gc/aafc/dina/service/ManagedAttributeService.java
https://redmine.biodiversity.agr.gc.ca/issues/22825
=> 22825 managed attribute service should not allow delete by default

dina-base-api/src/main/java/ca/gc/aafc/dina/i18n/MultilingualDescription.java, dina-base-api/src/main/java/ca/gc/aafc/dina/validation/ManagedAttributeValueValidator.java, dina-base-api/src/main/java/ca/gc/aafc/dina/validation/MultilingualDescriptionValidator.java, dina-base-api/src/main/resources/base-validation-messages.properties, dina-base-api/src/test/java/ca/gc/aafc/dina/validation/MultilingualDescriptionValidatorTest.java
https://redmine.biodiversity.agr.gc.ca/issues/23050
=> 23050 add new multilingual description related classes

dina-workbook/pom.xml, dina-workbook/src/main/java/ca/gc/aafc/dina/workbook/WorkbookConverter.java
Added isSupported with the only currently supported type for Excel sheet
=> 23090 Add isSupportedType to WorkbookConverter

dina-test-support/src/main/java/ca/gc/aafc/dina/testsupport/BaseRestAssuredTest.java
https://redmine.biodiversity.agr.gc.ca/issues/23139
=> 23139 add create uri builder to base rest assured test

dina-workbook/src/main/java/ca/gc/aafc/dina/workbook/WorkbookConverter.java
=> 23149 WorkbookConverter isSupportedType should be static

dina-base-api/src/main/java/ca/gc/aafc/dina/validation/ManagedAttributeValueValidator.java, dina-base-api/src/main/java/ca/gc/aafc/dina/validation/ValidationContext.java, dina-base-api/src/test/java/ca/gc/aafc/dina/service/ManagedAttributeServiceIT.java, dina-base-api/src/test/java/ca/gc/aafc/dina/validation/ManagedAttributeValueValidatorTest.java
Added possibility to provide a validation context
=> 23279 ManagedAttributeValueValidator should accept a context

dina-base-api/src/main/java/ca/gc/aafc/dina/security/KeycloakAuthConfig.java, pom.xml
https://redmine.biodiversity.agr.gc.ca/issues/23051
=> 23051 try spring boot 2.5.1

dina-base-api/src/main/java/ca/gc/aafc/dina/service/HierarchicalObject.java, dina-base-api/src/main/java/ca/gc/aafc/dina/service/PostgresHierarchicalDataService.java, dina-base-api/src/test/java/ca/gc/aafc/dina/service/PostgresHierarchicalDataServiceIT.java, dina-base-api/src/test/resources/create-test-data.sql
Added getHierarchyWithType and tests
=> 23434 Add getHierarchyWithType to PostgresHierarchicalDataService

dina-base-api/pom.xml
https://redmine.biodiversity.agr.gc.ca/issues/23442
=> 23442 update javers

dina-base-api/src/main/java/ca/gc/aafc/dina/jpa/BaseDAO.java, dina-base-api/src/main/java/ca/gc/aafc/dina/service/DefaultDinaService.java, dina-base-api/src/test/java/ca/gc/aafc/dina/service/DefaultDinaServiceTest.java
Added findOneById and fixed some comments
=> 23450 Add findOneById to DefaultDinaService

dina-base-api/pom.xml
https://redmine.biodiversity.agr.gc.ca/issues/23443
=> 23443 update my batis spring boot starter

dina-base-api/src/test/java/ca/gc/aafc/dina/jsonapi/DinaRepoRestIT.java
https://redmine.biodiversity.agr.gc.ca/issues/23471
=> 23471 add new integration test to test crnk update

dina-base-api/src/main/java/ca/gc/aafc/dina/exceptionmapping/ConstraintViolationExceptionMapper.java, dina-base-api/src/test/java/ca/gc/aafc/dina/dto/DepartmentDto.java, dina-base-api/src/test/java/ca/gc/aafc/dina/entity/Department.java, dina-base-api/src/test/java/ca/gc/aafc/dina/entity/Person.java, dina-base-api/src/test/java/ca/gc/aafc/dina/exceptionmapping/ConstraintViolationExceptionMapperIT.java
https://redmine.biodiversity.agr.gc.ca/issues/23513
=> 23513 improve constraint violation exception error message

dina-base-api/pom.xml
Set a different outputDirectory for delombok and make Javadoc using it.
=> 23535 Fixed delombok duplicated source file issue

pom.xml
=> 23538_update_spring_boot_253

pom.xml
=> 23856 Update dependency-check

dina-base-api/src/main/java/ca/gc/aafc/dina/DinaBaseApiAutoConfiguration.java, dina-base-api/src/test/java/ca/gc/aafc/dina/entity/Department.java, dina-base-api/src/test/java/ca/gc/aafc/dina/exceptionmapping/ConstraintViolationExceptionMapperIT.java, dina-base-api/src/test/java/ca/gc/aafc/dina/service/DinaServiceValidationLocaleIT.java, dina-base-api/src/test/resources/validation-messages.properties
https://redmine.biodiversity.agr.gc.ca/issues/24108
=> 24108 force resource bundle message source always use message format

dina-base-api/pom.xml
https://redmine.biodiversity.agr.gc.ca/issues/24223
=> 24223 update messaging api to 0.3

docs/authorization.adoc
update example for "Returning your permissions for an object" docs section
=> 24174_update_docs_for_returning_permissions_for_object

dina-base-api/src/main/java/ca/gc/aafc/dina/dto/HierarchicalObject.java, dina-base-api/src/main/java/ca/gc/aafc/dina/entity/HierarchicalObject.java, dina-base-api/src/main/java/ca/gc/aafc/dina/service/PostgresHierarchicalDataService.java, dina-base-api/src/test/java/ca/gc/aafc/dina/service/PostgresHierarchicalDataServiceIT.java
https://redmine.biodiversity.agr.gc.ca/issues/23933
=> 23933 change hierarchical object package

docs/authorization.adoc
update docs to include AttributeMetaInfoProvider
=> 24302 documentation on dina-base should mention AttributeMetaInfoProvider

dina-base-api/pom.xml
=> 24685 Update_dina-search

dina-base-api/pom.xml
updated Javers and dina-messaging
=> 24779 Update dependencies

dina-base-api/src/main/java/ca/gc/aafc/dina/extension/FieldExtensionDefinition.java
https://redmine.biodiversity.agr.gc.ca/issues/24872
=> 24872 create class field extension definition

dina-base-api/src/main/java/ca/gc/aafc/dina/repository/DinaRepository.java
https://redmine.biodiversity.agr.gc.ca/issues/25209
=> store idFieldName

dina-base-api/pom.xml
https://redmine.biodiversity.agr.gc.ca/issues/25817
=> 25817 update hibernate types

dina-base-api/src/test/java/ca/gc/aafc/dina/datetime/ISODateTimeTest.java
moved ISODateTimeTest from collection-api
=> 25821 Move ISODateTime tests

dina-base-api/pom.xml
https://redmine.biodiversity.agr.gc.ca/issues/25831
=> 25831 change hibernate types 52 dependency scope

dina-base-api/src/main/java/ca/gc/aafc/dina/validation/ManagedAttributeValueValidator.java, dina-base-api/src/test/java/ca/gc/aafc/dina/security/WithMockKeycloakUserIT.java, dina-base-api/src/test/java/ca/gc/aafc/dina/validation/ManagedAttributeValueValidatorTest.java
https://redmine.biodiversity.agr.gc.ca/issues/25975
=> 25975 update managed attribute value validator to validate custom errors and validation context

pom.xml
Updated SpringBoot, log4j2 and dependency-check
=> 26118 Update dependencies

owasp-suppression.xml, pom.xml
=> 26184 Update Keycloak to 15.1.x

dina-base-api/src/main/java/ca/gc/aafc/dina/i18n/MultilingualDescription.java
=> Feedback 26303

dina-base-api/src/main/java/ca/gc/aafc/dina/jpa/BaseDAO.java, dina-base-api/src/main/java/ca/gc/aafc/dina/service/DefaultDinaService.java
=> 26438 Expose flush method to DefaultService

dina-base-api/src/main/java/ca/gc/aafc/dina/repository/DinaRepository.java
Exposed DinaMappingLayer with a protected getter
=> 26520 Expose DinaMappingLayer in DinaRepository

dina-base-api/src/main/java/ca/gc/aafc/dina/extension/FieldExtensionDefinition.java, dina-base-api/src/test/java/ca/gc/aafc/dina/extension/FieldExtensionDefinitionIT.java, dina-base-api/src/test/resources/extension/cfia_ppc.yml
Added acceptedValues + utility methods to help validation
=> 26768 Allow acceptedValues on FieldExtensions

pom.xml
=> 26771 Update dependencies

dina-base-api/src/main/java/ca/gc/aafc/dina/security/spring/DinaPermissionEvaluator.java, dina-base-api/src/test/java/ca/gc/aafc/dina/security/spring/DinaPermissionEvaluatorTest.java
Added hasObjectOwnership and decided to not include admin checks
=> 26856 Add isSelfOrAdmin to DinaPermissionEvaluator

dina-test-support/src/main/java/ca/gc/aafc/dina/testsupport/TestResourceHelper.java, dina-test-support/src/test/java/ca/gc/aafc/dina/testsupport/TestResourceHelperTest.java
Added readContentAsJsonNode and a static instance of ObjectMapper that can be share.
=> 26858 Add utility method to load JSON from resource

dina-base-api/src/main/java/ca/gc/aafc/dina/jpa/BaseDAO.java, dina-base-api/src/main/java/ca/gc/aafc/dina/service/DefaultDinaService.java, dina-base-api/src/main/java/ca/gc/aafc/dina/service/ManagedAttributeService.java, dina-base-api/src/test/java/ca/gc/aafc/dina/jpa/BaseDAOIT.java, dina-base-api/src/test/java/ca/gc/aafc/dina/service/ManagedAttributeServiceIT.java
Added method to BaseDAO, DefaultDinService and a specialized implementation on ManagedAttributeService
=> 26860 Add findOneByProperties

pom.xml
=> 27065 Update SpringBoot

pom.xml
=> 27117 Update to SpringBoot 2.6.6

dina-base-api/pom.xml, dina-base-api/src/main/java/ca/gc/aafc/dina/DinaBaseApiAutoConfiguration.java
https://redmine.biodiversity.agr.gc.ca/issues/27171
=> Support #27171 - Add micrometer Timer metric

dina-base-api/src/main/java/ca/gc/aafc/dina/cache/MethodBasedKeyGenerator.java, dina-base-api/src/test/java/ca/gc/aafc/dina/cache/MethodBasedKeyGeneratorTest.java
=> 27300 Move MethodBasedKeyGenerator to base

pom.xml
Updated SpringBoot, dependecy-check and SpotBugs
=> 27313 Update SpringBoot

dina-base-api/src/main/java/ca/gc/aafc/dina/jpa/BaseDAO.java, dina-base-api/src/test/java/ca/gc/aafc/dina/jpa/BaseDAOIT.java, dina-base-api/src/test/resources/application.yml
https://redmine.biodiversity.agr.gc.ca/issues/27302
=> Support #27302 - Introduce entity graph

pom.xml
updated SpringBoot, Checkstyle and Spotbugs
=> 28128 Update SpringBoot

pom.xml
=> 28271 Update SpringBoot to 2.7

dina-base-api/src/main/java/ca/gc/aafc/dina/i18n/MultilingualTitle.java, dina-base-api/src/test/java/ca/gc/aafc/dina/i18n/MultilingualTest.java, dina-base-api/src/test/java/ca/gc/aafc/dina/service/DefaultDinaServiceTest.java
Added structure to support Multilangual titles
=> 28249 Add i18n MultilingualTitle

dina-base-api/src/test/java/ca/gc/aafc/dina/filter/RsqlFilterHandlerIT.java, dina-test-support/src/main/java/ca/gc/aafc/dina/testsupport/jsonapi/JsonAPITestHelper.java
Fixed toJsonAPIMap signature for relationships
Fixed RsqlFilterHandlerIT flaky test
=> 28134 Improve JsonAPITestHelper methods signature

dina-base-api/src/main/java/ca/gc/aafc/dina/jsonapi/JSONApiDocumentStructure.java, dina-base-api/src/test/java/ca/gc/aafc/dina/jsonapi/JSONApiDocumentStructureTest.java
Added new utility class JSONApiDocumentStructure
=> 28615 Move jsonapi utility function from search-api

dina-base-api/src/main/java/ca/gc/aafc/dina/security/GroupAuthorizationService.java, dina-base-api/src/test/java/ca/gc/aafc/dina/security/DinaGroupBasedPermissionsTest.java
Minimum role is now GUEST in the group for C and U and USER for D
=> 28684 Update GroupAuthorizationService

dina-base-api/src/main/java/ca/gc/aafc/dina/exceptionmapping/InternalServerErrorExceptionMapper.java, dina-base-api/src/test/java/ca/gc/aafc/dina/jsonapi/OperationJsonApiIT.java
Added a new Dina specific exception mapper for internal exceptions
=> 28802 Use TextHtmlSanitizer in exception mapping

dina-base-api/pom.xml, pom.xml
Updated SpringBoot, Javers and Hibernate Types
=> 28978 Update SpringBoot and dependencies

dina-workbook/pom.xml, pom.xml
Updated SnakeYAML, dependency-check and Apache POI
=> 28993 Update more dependencies

dina-base-api/src/main/java/ca/gc/aafc/dina/entity/StorageGridLayout.java, dina-base-api/src/test/java/ca/gc/aafc/dina/entity/StorageGridLayoutTest.java
Added isValidRow and isValidColumn
=> 28991 Add row and col validate method to StorageGridLayout

dina-base-api/src/main/java/ca/gc/aafc/dina/repository/DinaRepository.java, dina-base-api/src/test/java/ca/gc/aafc/dina/repository/DinaRepositoryIT.java
Used internal registry to focus checkSubmittedData on main attributes for known classes
=> 29325 Exclude relationships from checkSubmittedData

pom.xml
Updated SpringBoot, dependency-check and SpotBugs
=> 29330 Update dependencies

dina-base-api/src/main/java/ca/gc/aafc/dina/security/TextHtmlSanitizer.java, dina-base-api/src/test/java/ca/gc/aafc/dina/security/TextHtmlSanitizerTest.java
Added option to allow unescaped char
=> 29578 Improve isSafeText to allow unescaped char option

dina-base-api/pom.xml, dina-base-api/src/test/java/ca/gc/aafc/dina/repository/DinaRepositoryIT.java, pom.xml
Updated SpringBoot, dependency-check and Javers
=> 29659 Update dependencies

dina-base-api/src/main/java/ca/gc/aafc/dina/security/TextHtmlSanitizer.java, dina-base-api/src/test/java/ca/gc/aafc/dina/security/TextHtmlSanitizerTest.java
Added missing semicolon as accepted parse error
=> 29842 Adjust acceptableText

dina-base-api/src/main/java/ca/gc/aafc/dina/repository/DinaRepository.java
renamed supplyPredicate to supplyCheckSubmittedDataPredicate
=> 29795 Rename DinaRepository supplyPredicate

pom.xml
=> 29941 Update Keycloak to 19

dina-base-api/pom.xml, pom.xml
Updated SpringBoog, HibernateTypes and Javers
=> 30479 Update dependencies

dina-base-api/src/test/java/ca/gc/aafc/dina/jpa/BaseDAOIT.java
Fixed issue where the relationship was not saved + added coverage for it
=> 30533 BaseDAOIT resultListFromCriteria_withQueryHint test incomplete

dina-base-api/src/main/java/ca/gc/aafc/dina/validation/TypedVocabularyElementValidator.java
Changed to public so it can be reused in the different modules
=> 31137 TypedVocabularyElementValidator visibility issue

dina-base-api/src/main/java/ca/gc/aafc/dina/validation/TypedVocabularyElementValidator.java
Change method to public instead of package protected
=> 31227 TypedVocabularyElementValidator visibility issue on methods

dina-base-api/src/main/java/ca/gc/aafc/dina/service/MessageProducingService.java
Added new method signature to all operations to better control if a message should be emitted
=> 31414 Add to silent option to MessageProducingService

dina-test-support/src/main/java/ca/gc/aafc/dina/testsupport/elasticsearch/ElasticSearchTestUtils.java, dina-test-support/src/test/java/ca/gc/aafc/dina/testsupport/elasticsearch/ElasticSearchTestUtilsIT.java
Added refresh to indexDocument
=> 31691 ElasticSearchTestUtils indexDocument should use refresh

dina-base-api/src/main/java/ca/gc/aafc/dina/jsonapi/JSONApiDocumentStructure.java, dina-base-api/src/test/java/ca/gc/aafc/dina/jsonapi/JSONApiDocumentStructureTest.java
Added extractNestedMapUsingDotNotation method + test
=> 31694 Create JSONApiDocumentStructure extractNestedMapUsingDotNotation

dina-base-api/src/main/java/ca/gc/aafc/dina/jpa/BaseDAO.java, dina-base-api/src/test/java/ca/gc/aafc/dina/service/DinaObjectSummaryServiceIT.java
Added exception handling + test
=> 31972 Make findOneByQuery consistent

dina-base-api/src/main/java/ca/gc/aafc/dina/jsonapi/JSONApiDocumentStructure.java, dina-base-api/src/test/java/ca/gc/aafc/dina/jsonapi/JSONApiDocumentStructureTest.java
Added recursive call to the function + some utility methods
=> 31966 Allow recursive extractNestedMapUsingDotNotation

dina-base-api/src/main/java/ca/gc/aafc/dina/extension/FieldExtensionDefinition.java, dina-base-api/src/main/java/ca/gc/aafc/dina/vocabulary/VocabularyElement.java, dina-base-api/src/main/java/ca/gc/aafc/dina/vocabulary/VocabularyElementConfiguration.java
Move the annotation(s) on the interface
=> 31982 Validate VocabularyElement key

pom.xml
=> 31980 Upgrade Keycloak adapter to 20

dina-workbook/src/main/java/ca/gc/aafc/dina/workbook/SpreadsheetHelper.java, dina-workbook/src/test/java/ca/gc/aafc/dina/workbook/SpreadsheetHelperTest.java
Numeric cell with date format will now be returned as ISO string
=> 32080 Add support for numeric date with format on Workbook converter

dina-base-api/src/main/java/ca/gc/aafc/dina/exceptionmapping/IllegalStateExceptionMapper.java, dina-base-api/src/test/java/ca/gc/aafc/dina/exceptionmapping/IllegalStateExceptionMapperIT.java, dina-base-api/src/test/java/ca/gc/aafc/dina/exceptionmapping/UnknownAttributeExceptionMapperIT.java
Added exception mapper for IllegalStateException + test
=> 32256 Add exception mapper for IllegalStateException

dina-base-api/src/main/java/ca/gc/aafc/dina/config/DevSettings.java
getRolesPerGroup is now null-safe
=> 32009 Fix DevSettings default value

dina-base-api/src/main/java/ca/gc/aafc/dina/DinaBaseApiAutoConfiguration.java, dina-base-api/src/main/java/ca/gc/aafc/dina/crkn/PatchedCrnkErrorController.java
Added an updated implementation of CrnkErrorController + provide specific bean in configuration
=> 32288 Patch Crnk CrnkErrorController for SpringBoot 2.7

dina-base-api/pom.xml, dina-base-api/src/test/java/ca/gc/aafc/dina/entity/JsonbCar.java, dina-base-api/src/test/java/ca/gc/aafc/dina/entity/JsonbMethod.java, dina-base-api/src/test/java/ca/gc/aafc/dina/entity/Person.java, dina-base-api/src/test/java/ca/gc/aafc/dina/entity/ma/TestManagedAttribute.java
Updated dependency and includes
=> 32038 Migrate to hypersistence-utils

pom.xml
Updated SpringBoot and dependency-check
=> 32450 Update SpringBoot

dina-base-api/pom.xml, dina-test-support/pom.xml, pom.xml
Removed starter data jpa from parent pom file
=> 32693 Move spring-boot-starter-data-jpa dependency

dina-base-api/pom.xml, dina-base-api/src/test/java/ca/gc/aafc/dina/service/MessageProducingServiceTest.java
Updated search-messaging and related test
=> 32780 Update search-messaging library

dina-search/src/main/java/ca/gc/aafc/dina/search/config/ElasticSearchConfig.java, dina-search/src/main/java/ca/gc/aafc/dina/search/config/ElasticSearchProperties.java
Added default port for ElasticSearchConfig
=> 32779 Add better default for ElasticSearch port

dina-messaging/src/main/java/ca/gc/aafc/dina/messaging/message/ObjectExportNotification.java
Added ObjectExportNotification message class
=> 32877 Add ObjectExport message

dina-messaging/src/main/java/ca/gc/aafc/dina/messaging/message/ObjectExportNotification.java
=> 33168 Add name to ObjectExportNotification

dina-base-api/src/main/java/ca/gc/aafc/dina/config/ResourceNameIdentifierConfig.java, dina-base-api/src/main/java/ca/gc/aafc/dina/service/ResourceNameIdentifierService.java, dina-base-api/src/test/java/ca/gc/aafc/dina/TestDinaBaseApp.java, dina-base-api/src/test/java/ca/gc/aafc/dina/repository/ResourceNameIdentifierBaseRepositoryTest.java
Added ResourceNameIdentifierConfig to optionally config columns name to use
=> 33252 Allow to configure ResourceNameIdentifierService fields

dina-base-api/src/main/java/ca/gc/aafc/dina/jpa/BaseDAO.java, dina-base-api/src/main/java/ca/gc/aafc/dina/repository/ResourceNameIdentifierBaseRepository.java, dina-base-api/src/main/java/ca/gc/aafc/dina/service/ResourceNameIdentifierService.java, dina-base-api/src/test/java/ca/gc/aafc/dina/repository/ResourceNameIdentifierBaseRepositoryTest.java
Added new service and function to baseDAO to allow list with limit and offset
=> 33475 Allow to get resource-name-identifier without name

dina-base-api/src/main/java/ca/gc/aafc/dina/repository/ResourceNameIdentifierBaseRepository.java, dina-base-api/src/main/java/ca/gc/aafc/dina/security/auth/GroupAuth.java, dina-base-api/src/main/java/ca/gc/aafc/dina/security/auth/GroupWithReadAuthorizationService.java, dina-base-api/src/test/java/ca/gc/aafc/dina/repository/ResourceNameIdentifierBaseRepositoryTest.java
Added authorization service + utility classes and a Group based authorization service that will apply the permission on READ.
=> 33483 Add authorization to ResourceNameIdentifierBaseRepository

dina-base-api/pom.xml, dina-base-api/src/main/java/ca/gc/aafc/dina/dto/JsonApiPartialPatchDto.java, dina-base-api/src/test/java/ca/gc/aafc/dina/jsonapi/DinaRepositoryV2IT.java
Created Dto class + integration test for it and future RepositoryV2 code
=> 33512 Create JsonApiPartialPatchDto

dina-messaging/src/main/java/ca/gc/aafc/dina/messaging/message/ReportTemplateUploadNotification.java
Added class for ReportTemplateUploadNotification
=> 33560 Add report template notification

dina-messaging/src/main/java/ca/gc/aafc/dina/messaging/producer/RabbitMQMessageProducer.java, dina-messaging/src/test/java/ca/gc/aafc/dina/messaging/producer/RabbitMQTestProducer.java, dina-messaging/src/test/java/ca/gc/aafc/dina/messaging/producer/RabbitMQTestProducerQueue2.java
Removed generic and change method to accept interface DinaMessage
=> 33583 Make RabbitMQMessageProducer more generic

dina-base-api/src/main/java/ca/gc/aafc/dina/jpa/BaseDAO.java, dina-base-api/src/test/java/ca/gc/aafc/dina/jpa/BaseDAOIT.java
Removed resultListFromQuery, findAllByQuery should be used instead
=> 33750 Duplicated method in BaseDAO

dina-base-api/src/main/java/ca/gc/aafc/dina/security/DinaAuthenticatedUser.java, dina-base-api/src/main/java/ca/gc/aafc/dina/security/KeycloakAuthConfig.java, dina-base-api/src/main/java/ca/gc/aafc/dina/security/KeycloakClaimParser.java
Added attribute from Keycloak claim
=> 33831 Add attribute to identify service account

dina-base-api/src/main/java/ca/gc/aafc/dina/service/DefaultDinaService.java, dina-base-api/src/test/java/ca/gc/aafc/dina/repository/DinaRepositoryIT.java
Added new method to standardize group in DefaultDinaService
=> 34886 Add method to standardize group name

dina-workbook/src/main/java/ca/gc/aafc/dina/workbook/WorkbookConverter.java, dina-workbook/src/main/java/ca/gc/aafc/dina/workbook/WorkbookGenerator.java, dina-workbook/src/main/java/ca/gc/aafc/dina/workbook/WorkbookSheet.java, dina-workbook/src/test/java/ca/gc/aafc/dina/workbook/WorkbookGeneratorIT.java
Added option to give aliases to columns and write both columns and aliases in Workbook metadata. Removed deprecated method and added WorkbookSheet record
=> 35048 Add support for aliases in WorkbookGenerator

dina-base-api/src/main/java/ca/gc/aafc/dina/security/DevUserConfig.java
Added getter for username and internal id
=> 35138 Improve DevUserConfig

dina-base-api/pom.xml, dina-workbook/pom.xml
Updated apache poi, jsoup and common-io
=> 36069 Update dependencies

dina-base-api/src/main/java/ca/gc/aafc/dina/jpa/BaseDAO.java
Changed getNaturalIdFieldName implementation
=> 36483 Remove Crnk from BaseDAO

dina-base-api/src/main/java/ca/gc/aafc/dina/jpa/BaseDAO.java, dina-base-api/src/test/java/ca/gc/aafc/dina/jpa/BaseDAOIT.java
Use Apache lang utility method. Added test.
=> 36494 getNaturalIdFieldName not working for fields in parent class

dina-base-api/src/main/java/ca/gc/aafc/dina/exceptionmapping/JsonApiExceptionControllerAdvice.java
Added exception mapper for UnknownField exception
=> 36518 Provide exception mapper for unknown fields

dina-base-api/src/main/java/ca/gc/aafc/dina/mapper/DinaMappingRegistry.java, dina-base-api/src/main/java/ca/gc/aafc/dina/repository/DinaRepositoryV2.java, dina-json/src/main/java/ca/gc/aafc/dina/jsonapi/JsonApiImmutable.java
Allow more than 1 JsonApiImmutable value
=> 36872 Improve DinaMappingRegistry
