- src/main/java/ca/gc/aafc/dina/jpa/BaseDAO.java
- src/test/java/ca/gc/aafc/dina/jpa/BaseDAOIT.java
Renamed setRelationshipUsing to setRelationshipByNaturalIdReference. Also change NaturalId parameter to object instead of UUID.
> Support #19078 Rename BaseDAO setRelationshipUsing

- dina-base-api/src/main/java/ca/gc/aafc/dina/jpa/DinaService.java
Adds findOneReferenceByNaturalId to Dina Service.
This is a delegater method only and can be considered tested through the base dao.
> 19364_dina_service_get_reference_by_natural_id

- dina-base-api/src/main/java/ca/gc/aafc/dina/repository/DinaRepository.java
- dina-base-api/src/test/java/ca/gc/aafc/dina/repository/DinaRepositoryIT.java
This enables the dina repo to return meta information (total resource count) and exclude top level links during find all requests.
This is a slightly different implementation then stated on the original ticket for the following reason.
Dina repo find all is currently not using the dina service but instead leverages crnks jpa modules. As dina service is not used in this way, adding a DinaService.GetCount would be unnecessary at this time.
We can always change the approach if need be
> 19377 dina repo meta info

- dina-base-api/src/main/java/ca/gc/aafc/dina/mapper/DinaMapper.java
Small bug fix for accessing resolver map before checking for a key.
was causing a null pointer.
> 19666_dina_mapper_null_pointer_when_no_resolver_source

- dina-base-api/src/main/java/ca/gc/aafc/dina/mapper/DinaMapper.java
- dina-base-api/src/test/java/ca/gc/aafc/dina/mapper/DinaMapperTest.java
There are situations where a DTO will have relations that are not present on the entity. 
The changes here will ignore relations that are not present on the entity as they are not mapped anyways.
> 19783 dina mapper null pointer when no related entity

- dina-base-api/src/main/java/ca/gc/aafc/dina/mapper/DinaMapper.java
Moves a portion of reflective operations for the dina mapper to the initialization of the mapper.
Each mapping request will use initialized maps to track what it needs during the mapping process.
> 19814 mapper reflection performance improvements

- dina-base-api/pom.xml
- dina-base-api/src/main/java/ca/gc/aafc/dina/service/AuditService.java
- dina-base-api/src/test/java/ca/gc/aafc/dina/DinaUserConfig.java
- dina-base-api/src/test/java/ca/gc/aafc/dina/dto/EmployeeDto.java
- dina-base-api/src/test/java/ca/gc/aafc/dina/service/AuditServiceIT.java
- Introducing AuditService.java
- Allows javers snapshot repository access. Bean is accessible through enviroment property: 
`@ConditionalOnProperty(value = "dina.auditing.enabled", havingValue = "true")`
- Test should prove the interface is behaving as expected.
> 19994 add audit service

- dina-base-api/src/main/java/ca/gc/aafc/dina/dto/AuditSnapshotDto.java
- dina-base-api/src/main/java/ca/gc/aafc/dina/repository/auditlog/AuditSnapshotRepository.java
- dina-base-api/src/test/java/ca/gc/aafc/dina/repository/AuditSnapshotRepositoryIT.java
Introduces the Audit Snapshot Repository. 
Provides an endpoint to request audit snap shots.
Activated with the property `dina.auditing.enabled=true`
> 19995 add audit repo

- dina-base-api/src/main/java/ca/gc/aafc/dina/service/DinaService.java
Dina service is no longer abstract. You can create and use the class without implementing it.
find all and get resource count are generically separate from Dina service para type.
DinaService use of generics still make sense for create and pre create type operations to use the same type.
> 20138 enhance dina service

- dina-base-api/pom.xml
- dina-base-api/src/test/java/ca/gc/aafc/dina/jsonapi/DinaRepoBulkOperationIT.java
Adds a test suite to test that the dina repo can support the basic Bulk operations module provided by crnk.
The main edge cases for the test are as follows:
- Bulk Post of a resource with basic attributes and a relationship
- Bulk Update of a resource's basic attributes and relationship
- Bulk deleting a resource
> 20252 dina repo operations it

- dina-base-api/src/main/java/ca/gc/aafc/dina/repository/DinaRepository.java
- dina-base-api/src/test/java/ca/gc/aafc/dina/jsonapi/DinaRepoBulkOperationIT.java
- dina-base-api/src/test/java/ca/gc/aafc/dina/repository/DinaRepositoryIT.java
Major change is that DinaRepo.findAll will always return the relationships that are NOT included in the query spec in a shallow form (id only).
This allows the crnk pre patch operation for a Patch request to give the Repo.save() method the correct information needed to persist the correct state of a resource.
Implemented in the repo layer, handles relations that are collections.
> 20342 partial update dina repo wipes relationship

- dina-base-api/src/main/java/ca/gc/aafc/dina/repository/DinaRepository.java
- dina-base-api/src/main/java/ca/gc/aafc/dina/repository/meta/DinaMetaInfo.java
- dina-base-api/src/test/java/ca/gc/aafc/dina/jsonapi/DinaRepoRestIT.java
Fixes external relation section in meta to conform with the specs
```
"external": [
{
"type": "agent",
"href": "Agent/api/v1/agent"
},
{
"type": "author",
"href": "Author/api/v1/author"
}
]
```
> 20632 external relation meta section fix

- dina-base-api/src/main/java/ca/gc/aafc/dina/mapper/CustomFieldHandler.java
- dina-base-api/src/main/java/ca/gc/aafc/dina/mapper/CustomFieldResolver.java
- dina-base-api/src/test/java/ca/gc/aafc/dina/mapper/DinaMapperTest.java
Changes custom field resolvers to be declared on the fields that need them as opposed to the methods that will apply them.
general usesage like the following
```
public static final class NestedResolverRelation {
// Custom Resolved Field to test
@CustomFieldResolver(setterMethod = "nameToEntity")
private ComplexObject name;
public ComplexObject nameToEntity(NestedResolverRelationDTO dto) {
...
}
}
```
> 20819 method on custom field resolver

- dina-base-api/src/main/java/ca/gc/aafc/dina/service/AuditService.java
- dina-base-api/src/test/java/ca/gc/aafc/dina/service/AuditServiceIT.java
Updates the AuditService to support the removal of audit snap shots from the Javers DB tables.
> 20832 support removal of audit snapshots

- dina-base-api/src/main/java/ca/gc/aafc/dina/security/DevUserConfig.java
- dina-base-api/src/main/java/ca/gc/aafc/dina/security/DinaAuthenticatedUser.java
- dina-base-api/src/main/java/ca/gc/aafc/dina/security/KeycloakAuthConfig.java
- dina-base-api/src/test/java/ca/gc/aafc/dina/security/WithMockKeycloakUserIT.java
- dina-test-support/src/main/java/ca/gc/aafc/dina/testsupport/security/WithMockKeycloakSecurityContextFactory.java
- dina-test-support/src/main/java/ca/gc/aafc/dina/testsupport/security/WithMockKeycloakUser.java
Updates the authenticated user to support a new claim in the token. the internal identifier.
The token parsing and mocker user test support has also been updated.
> 21196 authorized user id reference

- dina-base-api/src/main/java/ca/gc/aafc/dina/jpa/BaseDAO.java
- dina-base-api/src/main/java/ca/gc/aafc/dina/jpa/PredicateSupplier.java
- dina-base-api/src/main/java/ca/gc/aafc/dina/service/DefaultDinaService.java
- dina-base-api/src/main/java/ca/gc/aafc/dina/service/DinaService.java
Expand the dina interface to allow access to predicate building with the entity manager.
This is a requirement of Rsql.
We tighten up definition of what actually can supply predicates to the dina service with a new functional interface.
```
@FunctionalInterface
interface DinaPredicateSupplier<T> {
Predicate[] supply(CriteriaBuilder criteriaBuilder, Root<T> root, EntityManager em);
}
```
We over load two additional methods and chain them up to existing methods using our new interface.
Test should verify everything is working as expected.
> 21971 expand dina service for rsql

- dina-base-api/src/main/java/ca/gc/aafc/dina/jpa/BaseDAO.java
- dina-base-api/src/main/java/ca/gc/aafc/dina/jpa/PredicateHelper.java
- dina-base-api/src/main/java/ca/gc/aafc/dina/service/ManagedAttributeService.java
- dina-base-api/src/main/java/ca/gc/aafc/dina/validation/ManagedAttributeValueValidator.java
- dina-base-api/src/main/java/ca/gc/aafc/dina/validation/ValidationContext.java
- dina-base-api/src/main/resources/base-validation-messages.properties
- dina-base-api/src/test/java/ca/gc/aafc/dina/service/ManagedAttributeServiceIT.java
- dina-base-api/src/test/java/ca/gc/aafc/dina/validation/ManagedAttributeValueValidatorTest.java
Added findAttributesForValidation that a subclass can override to make use of the validation context.
> 27057 Allow ManagedAttributeValueValidator to use ValidationContext

- dina-test-support/src/main/java/ca/gc/aafc/dina/testsupport/BaseRestAssuredTest.java
- dina-test-support/src/test/java/ca/gc/aafc/dina/testsupport/BaseRestAssuredTestIT.java
Configure restassured to use utf8 on jsonapi content type
> 28110 Set default to utf8 on jsonapi encoding for restassured

- dina-base-api/src/main/resources/checkstyle.xml
edu.umd.cs.findbugs.annotations should be used instead
> 31676 Replace nullable and nonnull annotations

- dina-base-api/src/main/java/ca/gc/aafc/dina/validation/VocabularyBasedValidator.java
- Refactored functions to use <? extends VocabularyElementConfiguration> where necessary
> 35663 Refactor VocabularyBased Validator to use bounded wildcard type

- dina-base-api/src/main/java/ca/gc/aafc/dina/repository/DinaRepositoryV2.java
- dina-base-api/src/main/java/ca/gc/aafc/dina/repository/JsonApiModelBuilderHelper.java
Added JsonApiModelBuilderHelper and moved related functions
> 35779 Move JsonApiModelBuilder related functions to its own class
